name:  Build & Push

on:
  push:
    branches: [ main ]

env:
  FASTAPI_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/devops-fastapi
  NGINX_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/devops-nginx

jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: docker/setup-buildx-action@v3
      
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build & Push FastAPI
        uses: docker/build-push-action@v5
        with:
          context: ./app
          push: true
          tags: |
            ${{ env.FASTAPI_IMAGE }}:latest
            ${{ env.FASTAPI_IMAGE }}:${{ github.run_number }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Build & Push NGINX
        uses: docker/build-push-action@v5
        with:
          context: ./nginx
          push: true
          tags: |
            ${{ env.NGINX_IMAGE }}:latest
            ${{ env.NGINX_IMAGE }}:${{ github.run_number }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Summary
        run: |
          echo " Images pushed:"
          echo "  ${{ env.FASTAPI_IMAGE }}:latest"
          echo "  ${{ env.FASTAPI_IMAGE }}:${{ github.run_number }}"
          echo "  ${{ env.NGINX_IMAGE }}:latest"
          echo "  ${{ env.NGINX_IMAGE }}:${{ github.run_number }}"
